### ISSUE TITLE
Update sageQFeatures() default arguments with new sage output.

### ISSUE THREAD

**Issue by samgregoire** [UCLouvain-CBIO/sager#1]
The  `sageQFeatures()` function uses `byQuant `and `byId `arguments with the following default values:  
```
byQuant = c("file", "scannr"),
byId = c("filename", "scannr")
```
sage unified its output column names. It now uses "filename" in the quant file, similar to the id file, which produces an error when `byQuant` default values are not manually specified.

**Comment by lgatto** [comment]
Takes, will change de default values. In the meantime, you can set the parameters to the new values.
