### ISSUE TITLE
Update sagePSM() default arguments with new sage output.

### ISSUE THREAD

**Issue by samgregoire** [UCLouvain-CBIO/sager#2]
Since [v0.13.0](https://github.com/lazear/sage/blob/master/CHANGELOG.md#v0130), sage has

> Changed "_fdr" columns to "_q" (e.g. "spectrum_q") in "results.sage.tsv" file

The function `sagePSM()` still uses `fdr = "spectrum_fdr"` as a default argument. This should be changed to `fdr = "spectrum_q"` to match sage output.

**Comment by lgatto** [comment]
Fixed in version 0.3.2

**Comment by sme229** [comment]
Hi @samgregoire 
Could you please share how did you import your tsv files? I'm getting this error: 
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column 

qf <- sageQFeatures(
quantTable = "lfq.tsv",
idTable = "results.sage.tsv",
byQuant = c("filename", "scannr"),
byId = c("filename", "scannr"),
splitBy = byQuant[1],
quantPattern = "lfq_",
)

**Comment by lgatto** [comment]
This is not related to #3
